version: '3.8'

services:
  imperva-attack-analytics:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./reports:/app/reports
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    container_name: imperva-attack-analytics-reporter
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/reports"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s